api_key: sk-hnobnlsgbethdjpsopkflppjezpntlwujdxxicrdheawqxfi
base_url: https://api.siliconflow.cn/v1/
embedding_model:
  api_key: ${SILICONFLOW_API_KEY}
  api_url: https://api.siliconflow.cn/v1/embeddings
  model_name: BAAI/bge-m3
  name: text-embedding-3-large
  type: silicon_flow
environment:
  api_key: ${SILICONFLOW_API_KEY}
  default_timeout: 10.0
  disable_proxy: true
  encoding: utf-8
  no_proxy: '*'
reranker:
  api_key: ${SILICONFLOW_API_KEY}
  api_url: https://api.siliconflow.cn/v1/rerank
  model_name: BAAI/bge-reranker-v2-m3
  return_documents: false
  top_n: 5
  type: siliconflow_native
singleton: true
