categories:
  auth_settings:
    settings:
      admin_password:
        description: 管理员密码
        is_secret: true
        type: string
        value: 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
    title: 认证设置
  behavior_settings:
    settings:
      auto_message:
        content:
          description: 自动消息内容
          type: string
          value: 请你模拟系统设置的角色，在微信上找对方聊天
        countdown:
          max_hours:
            description: 最大倒计时时间（小时）
            type: number
            value: 3.0
          min_hours:
            description: 最小倒计时时间（小时）
            type: number
            value: 1.0
      context:
        avatar_dir:
          description: 人设目录（自动包含 avatar.md 和 emojis 目录）
          type: string
          value: data/avatars/MONO
        max_groups:
          description: 最大上下文轮数
          type: number
          value: 30
      quiet_time:
        end:
          description: 安静时间结束
          type: string
          value: 08:00
        start:
          description: 安静时间开始
          type: string
          value: '22:00'
    title: 行为设置
  llm_settings:
    settings:
      api_key:
        description: DeepSeek API密钥
        is_secret: true
        type: string
        value: ''
      base_url:
        description: DeepSeek API基础URL
        type: string
        value: https://api.siliconflow.cn/v1/
      max_tokens:
        description: 回复最大token数量
        type: number
        value: 1000
      model:
        description: 使用的AI模型名称
        options:
        - deepseek-ai/DeepSeek-V3
        - Pro/deepseek-ai/DeepSeek-V3
        - Pro/deepseek-ai/DeepSeek-R1
        type: string
        value: deepseek-ai/DeepSeek-V3
      temperature:
        description: AI回复的温度值
        max: 1.5
        min: 0.5
        type: number
        value: 1.2
    title: 大语言模型配置
  media_settings:
    settings:
      image_generation:
        model:
          description: 图像生成模型
          type: string
          value: deepseek-ai/Janus-Pro-7B
        temp_dir:
          description: 临时图片存储目录
          type: string
          value: data/images/temp
      image_recognition:
        api_key:
          description: Moonshot AI API密钥（用于图片和表情包识别）
          is_secret: true
          type: string
          value: ''
        base_url:
          description: Moonshot API基础URL
          type: string
          value: https://api.moonshot.cn/v1
        model:
          description: 图像识别 AI 模型
          type: string
          value: moonshot-v1-8k-vision-preview
        temperature:
          description: Moonshot AI的温度值
          max: 2
          min: 0
          type: number
          value: 0.7
      text_to_speech:
        tts_api_url:
          description: TTS服务API地址
          type: string
          value: http://127.0.0.1:5000/tts
        voice_dir:
          description: 语音文件存储目录
          type: string
          value: data/voices
    title: 媒体设置
  rag_settings:
    settings:
      api_key: ''
      base_url: ''
      embedding_model: text-embedding-3-large
      is_rerank: false
      reranker_model: gpt-4o-mini-2024-07-18
      top_k: 5
    title: rag记忆配置
  user_settings:
    settings:
      listen_list:
        description: 要监听的用户列表（请使用微信昵称，不要使用备注名）
        type: array
        value:
        - ''
    title: 用户设置
